language: node_js
node_js:
  - '18'

env:
  global:
    - CXX=g++-9 # Update to a newer g++ version for better C++ standards support
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9 # Ensure compatibility with newer Node.js versions and their native modules
before_install:
  # If you're working with Electron, you might need to install specific versions of it
  - npm install -g electron@latest # Or specify the Electron version you're targeting
  - npm install -g node-gyp # Ensure the latest node-gyp is used
script:
  - npm test # Your test script here
  # Any other commands you need to run for testing
